### ISSUE TITLE
RSS does not work.

### ISSUE THREAD

**Issue by ahmetcadirci25** [yujixr/instarss#4]
Can you check it?

https://rss.yuji.ne.jp/instagram/airbus.xml
https://rss.yuji.ne.jp/instagram/instagram.xml

**Comment by yujixr** [comment]
Sorry for your inconvenience.😞

The RSS generator cannot fetch data from instagram server, due to access limitation.
I'm trying to resolve this problem by blocking some requests. But it might need a time.

**Comment by igor-akhmetov** [comment]
Not sure if helpful, but there's some info about Instagram blocking policy on https://git.sr.ht/~cadence/bibliogram-docs/tree/master/docs/Instagram%20rate%20limits.md#tldr-what-does-it-mean-if-an-instance-is-blocked.

**Comment by yujixr** [comment]
Thanks. But according to this article, we're never allowed to access Instagram's user page from cloud servers.
`instarss` is running on [Cloudflare Workers](https://workers.cloudflare.com/), so this program may not work again....

I have no ideas....

**Comment by ahmetcadirci25** [comment]
There is an active JS library. Might help.

https://github.com/ismail0234/instagram-feed

**Comment by yujixr** [comment]
It's been a while.
After much deliberation, I've decided to stop providing this RSS generator. The source code will remain open to the public, so if you want to continue using it, please host it yourself.
I apologize for the inconvenience, and thank you for your patience.
